USE [master]
GO
/****** Object:  Database [Taquero]    Script Date: 07/19/2020 20:55:56 ******/
CREATE DATABASE [Taquero] ON  PRIMARY 
( NAME = N'Taquero', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Taquero.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Taquero_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Taquero_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Taquero] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Taquero].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Taquero] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Taquero] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Taquero] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Taquero] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Taquero] SET ARITHABORT OFF
GO
ALTER DATABASE [Taquero] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Taquero] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Taquero] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Taquero] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Taquero] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Taquero] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Taquero] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Taquero] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Taquero] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Taquero] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Taquero] SET  DISABLE_BROKER
GO
ALTER DATABASE [Taquero] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Taquero] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Taquero] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Taquero] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Taquero] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Taquero] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Taquero] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Taquero] SET  READ_WRITE
GO
ALTER DATABASE [Taquero] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Taquero] SET  MULTI_USER
GO
ALTER DATABASE [Taquero] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Taquero] SET DB_CHAINING OFF
GO
USE [Taquero]
GO
/****** Object:  Table [dbo].[tacos]    Script Date: 07/19/2020 20:55:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tacos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[cantidad] [nchar](10) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[tacos] ON
INSERT [dbo].[tacos] ([id], [nombre], [cantidad]) VALUES (1, N'bisteck', N'10        ')
INSERT [dbo].[tacos] ([id], [nombre], [cantidad]) VALUES (2, N'chorizo', N'20        ')
INSERT [dbo].[tacos] ([id], [nombre], [cantidad]) VALUES (3, N'chicharron', N'35        ')
SET IDENTITY_INSERT [dbo].[tacos] OFF
